AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - db/migrate/20221118043632_create_retored_tables.rb
    - db/schema.rb
    - db/migrate/20221118043633_fix_db.rb
    - db/migrate/*_create_active_storage_tables.active_storage.rb
    - db/seeds.rb
    - db/quatro.rb
    - db/spesdb.rb
    - db/each_csv.rb
    - bin/*
    - vendor/**/*
    - config/environments/*
    - spec/rails_helper.rb
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - "config/environments/*.rb"

Metrics/ClassLength:
  Max: 600

Metrics/AbcSize:
  Max: 70

Metrics/MethodLength:
  Max: 10

Style/RescueStandardError:
  Enabled: false